#==============================================================================
# CHECKOV CONFIGURATION
#==============================================================================

framework:
  - terraform
quiet: true
soft-fail: false

#==============================================================================
# SKIPPED CHECKS
#==============================================================================

skip-check:
  - CKV_AWS_91
  - CKV_AWS_131
  - CKV_AWS_273
  - CKV_AWS_40
